config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    devise_for :users
    root "tours#index"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "sessions/new"
    resources :tours, only: %i(index show) do
      resources :bookings, except: %i(index), shallow: true
      resources :reviews, except: %i(index), shallow: true
    end
    resources :reviews, only: %i(index show) do
      resources :comments, only: %i(create destroy edit update)
    end
    resources :bookings, only: %i(index)
    resources :categories, only: %i(index show)
    namespace :admin do
      get "dasboard/index", to: "dasboard#index"
      patch "tours/status/:id", to: "tours#status", as: "status"
      resources :users
      resources :categories
      resources :tours
      resources :bookings
      resources :reviews
    end
  end
end

app/models/tour.rb
class Tour < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :images, dependent: :destroy
  belongs_to :category
  enum status: %i(close open)

  validates :name, presence: true, length: {maximum: Settings.size.length_max_255}
  validates :date_from, presence: true
  validates :date_to, presence: true
  validates :location_from, presence: true, length: {maximum: Settings.size.length_max_255}
  validates :location_to, presence: true, length: {maximum: Settings.size.length_max_255}
  validates :price, presence: true
  validates :max_people, presence: true, numericality: true
  validates :min_people, presence: true, numericality: true
  validates :description, presence: true, length: {maximum: Settings.size.text_2000}

  scope :select_custom, -> {select :id, :status, :name, :date_from, :date_to, :location_from,
    :location_to, :price, :max_people, :min_people, :description}
  scope :is_open, -> {where status: :open}
  scope :show_tour_desc, -> {order created_at: :desc}
end

app/controllers/admin/tours_controller.rb
class Admin::ToursController < Admin::BaseController
  before_action :load_tour, except: %i(new index create)
  before_action :load_cate, except: %i(index show destroy)

  def index
    @q = Tour.ransack params[:q]
    @tours = @q.result(distinct: true)
      .select_custom.show_tour_desc
      .page(params[:page]).per Settings.page.page_number_admin
  end

  def new
    @tour = Tour.new
    @image = @tour.images.build
  end

  def create
    @tour = Tour.new tour_params
    ActiveRecord::Base.transaction do
      @tour.save
      params[:images]["image_link"].each do |image|
        @image = Image.create! tour_id: @tour.id, image_link: image
      end
      flash[:success] = t "create_success"
      redirect_to admin_tours_path
    end
    rescue Exception
      flash[:danger] = t "not_image"
      render :new
  end

  def show
    @images = @tour.images.select_image
      .page(params[:page]).per Settings.page.page_number_img
  end

  def edit; end

  def update
    ActiveRecord::Base.transaction do
      @tour.update tour_params
      params[:images]["image_link"].each do |image|
        @image = Image.create! tour_id: @tour.id, image_link: image
      end
      flash[:success] = t "update_success"
      redirect_to admin_tours_path
    end
    rescue Exception
      flash[:danger] = t "not_image"
      render :edit
  end

  def destroy
    begin
      @tour.destroy
      flash[:success] = t "delete_success"
    rescue
      flash[:danger] = t "not_delete"
    end
    redirect_to admin_tours_path
  end

  def status
    if @tour.close?
      @tour.update! status: "open"
    elsif @tour.open?
      @tour.update! status: "close"
    end
    respond_to do |format|
      format.js
    end
  end

  private

  def tour_params
    params.require(:tour).permit :status, :name, :date_from, :date_to, :location_from, :location_to, :price,
      :max_people,:min_people, :description, :category_id
  end

  def load_tour
    @tour = Tour.find_by id: params[:id]
    return if @tour.present?
    flash[:danger] = t "tours.not_tour"
    redirect_to root_path
  end

  def load_cate
    @categories = Category.show_cate
  end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
  before_action :find_tour, only: %i(show)

  def index
    @q = Tour.ransack params[:q]
    @categories = Category.select_custom.order_lft_asc
    @tours = @q.result.select_custom.show_tour_desc.is_open
      .page(params[:page]).includes(:images).per Settings.tours.per_page
  end

  def show
    @booking = Booking.new
    @reviews = @tour.reviews
  end

  private

  def find_tour
    @tour = Tour.find_by id: params[:id]
    return if @tour
    flash[:danger] = t "tours.not_found"
    redirect_to tours_path
  end
end

app/views/admin/tours/_form.html.erb
<%= form_for [:admin, @tour] do |f| %>
  <div class="box-body">
    <%= render "admin/shared/error_messages", object: @tour %>
    <div class="col-sm-6 col-md-6 col-sx-12">
      <div class="form-group">
        <%= f.label :status, t("status") %><br>
        <div class="input-group">
          <span class="input-group-addon">
            <i class="fa fa-adjust style-icon"></i>
          </span>
          <%= f.select :status, Tour.statuses.keys, {}, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :name, t("name") %><br>
        <div class="input-group">
          <span class="input-group-addon">
            <i class="fa fa-newspaper-o style-icon"></i>
          </span>
          <%= f.text_field :name, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :date_from, ("Date - from") %><br>
        <div class="input-group">
          <span class="input-group-addon">
            <i class="fa fa-calendar style-icon"></i>
          </span>
          <%= f.date_field :date_from, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
       <%= f.label :date_to, t("tours.date_to") %><br>
        <div class="input-group">
          <span class="input-group-addon">
            <i class="fa fa-calendar style-icon"></i>
          </span>
          <%= f.date_field :date_to, class: "form-control" %>
        </div>
      </div>
       <div class="form-group">
        <%= f.label :price, t("tours.price") %><br>
        <div class="input-group">
          <span class="input-group-addon">
            <i class="fa fa-shopping-basket style-icon"></i>
          </span>
          <%= f.text_field :price, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.fields_for :images do |p| %>
        <div class="field">
          <%= p.label :image_link %><br>
          <%= p.file_field :image_link, multiple: true, name: "images[image_link][]", class: "upload-image",
            accept: "image/jpeg,image/gif,image/png" %>
        </div>
      <% end %>
      </div>
    </div>
    <div class="col-sm-6 col-md-6 col-sx-12">
     <div class="form-group">
        <%= f.label :location_from, t("tours.location_from") %><br>
        <div class="input-group">
          <span class="input-group-addon">
            <i class="fa fa-map-marker style-icon"></i>
          </span>
          <%= f.text_field :location_from, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :location_to, t("tours.location_to") %><br>
        <div class="input-group">
          <span class="input-group-addon">
            <i class="fa fa-map-marker style-icon"></i>
          </span>
          <%= f.text_field :location_to, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :max_people, t("tours.max_people") %><br>
        <div class="input-group">
          <span class="input-group-addon">
            <i class="fa fa-user-circle-o style-icon"></i>
          </span>
          <%= f.text_field :max_people, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :min_people, t("tours.min_people") %><br>
        <div class="input-group">
          <span class="input-group-addon">
            <i class="fa fa-user-circle style-icon"></i>
          </span>
          <%= f.text_field :min_people, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :description, t("tours.description") %><br>
        <div class="input-group">
          <span class="input-group-addon">
            <i class="fa fa-commenting-o style-icon"></i>
          </span>
          <%= f.text_field :description, class: "form-control" %>
        </div>
      </div>
      <div class="form-group">
        <%= f.label :Category, t("category") %><br>
        <div class="input-group">
          <span class="input-group-addon">
            <i class="fa fa-list-alt style-icon"></i>
          </span>
          <%= f.select :category_id, @categories.collect {|c| [c.name, c.id]},
            {}, class: "form-control" %>
        </div>
      </div>
    </div>
    <div class="col-sm-12 col-md-12 col-sx-12">
       <%= f.submit t("submit"), class: "btn btn-primary button-full" %>
    </div>
  </div>
<% end %>

app/views/admin/tours/_status.html.erb
 <% if tour.close? %>
  <%= link_to t("tours.btn_close"), admin_status_path(tour),class: "btn btn-danger fa fa-close", method: :patch, remote: true %>
  <% else %>
  <%= link_to t("tours.btn_open"), admin_status_path(tour),class: "btn btn-success fa fa-check-circle", method: :patch, remote: true %>
<% end %>

app/views/admin/tours/edit.html.erb
<% provide :title, t("tours.edit_title_tour") %>
<div class="col-xs-12">
  <div class="box">
    <div class="box-header">
        <h3 class="box-title"><%= t "edit_tour" %></h3>
    </div>
    <%= render "admin/tours/form" %>
  </div>
</div>

app/views/admin/tours/index.html.erb
<% provide :title, t("tours.admin_tour") %>
<div class="col-sm-12 col-md-12 col-xs-12">
  <div class="box">
    <div class="box-header">
      <h3 class="box-title"><i class="fa fa-list-alt icon_user" id="icon_list"></i>
        <%= t "list_tour" %>
      </h3>
      <div class="box-tools">
        <%= search_form_for [:admin, @q] do |f| %>
        <div class="input-group input-group-sm text-right" id="input_search">
          <%= f.text_field :name_or_location_from_or_location_to_cont, placeholder: t("look_for_tour"), class: "form-control" %>
          <div class="input-group-btn">
            <%= f.submit class: "btn btn-default fa fa-search" %>
          </div>
        </div>
        <% end %>
      </div>
    </div>
    <div class="box-body table-responsive no-padding">
      <table class="table table-responsive table-hover table-bordered border-user">
        <thead class="bordered-blueberry table_color">
          <tr>
            <th class="index_number"><%= t "index" %></th>
            <th class="text-center"><%= t "name" %></th>
            <th class="width_from text-center"><%= t "tours.date_from" %></th>
            <th class="width_from text-center"><%= t "tours.date_to" %></th>
            <th class="width_local text-center"><%= t "tours.location_from" %></th>
            <th class="width_local text-center"><%= t "tours.location_to" %></th>
            <th class="text-center"><%= t "tours.price" %></th>
            <th class="text-center"><%= t "tours.status" %></th>
            <th class="text-right"><%= link_to t("add"), new_admin_tour_path, class: "btn btn-primary fa fa-car icon_add" %></th>
          </tr>
        </thead>
        <tbody>
          <% @tours.each_with_index do |tour, index| %>
          <tr>
            <td><%= pages_number index, params[:page] %></td>
            <td><%= tour.name.truncate Settings.tours.truncate %></td>
            <td><%= tour.date_from %></td>
            <td><%= tour.date_to %></td>
            <td><%= tour.location_from %></td>
            <td><%= tour.location_to %></td>
            <td class="text-right"><%= tour.price.round Settings.tours.round %></td>
            <td class="text-center" id="tour_status-<%= tour.id %>">
              <% if tour.close? %>
                <%= link_to t("tours.btn_close"), admin_status_path(tour),class: "btn btn-danger fa fa-close", method: :patch, remote: true %>
              <% else %>
                 <%= link_to t("tours.btn_open"), admin_status_path(tour),class: "btn btn-success fa fa-check-circle", method: :patch, remote: true %>
              <% end %>
            </td>
            <td class="action text-center">
              <%= link_to t("show"), admin_tour_path(tour), class: "btn btn-info fa fa-info-circle" %>
              <%= link_to t("edit"), edit_admin_tour_path(tour), class: "btn btn-success fa fa-edit"%>
              <%= link_to t("del"), admin_tour_path(tour), class: "btn btn-danger fa fa-trash", method: :delete,
                  data: {confirm: t("are_you_sure")} %>
            </td>
          </tr>
          <% end %>
        </tbody>
        </thead>
      </table>
      <div class="text-right pages_custom">
        <%= paginate @tours, theme: 'twitter-bootstrap-3' %>
      </div>
    </div>
  </div>
</div>

app/views/admin/tours/new.html.erb
<% provide :title, t("tours.new_title_tour") %>
<div class="col-xs-12">
  <div class="box">
    <div class="box-header">
        <h3 class="box-title"><%= t "tours.add_tour" %></h3>
    </div>
    <%= render "admin/tours/form" %>
  </div>
</div>

app/views/admin/tours/show.html.erb
<% provide :title, t("tours.show_tour") %>
<div class="col-sm-12 col-md-12 col-xs-12">
  <div class="box">
    <div class="box-header">
      <h3 class="box-title"><i class="fa fa-exclamation-circle icon_user"></i>
        <%= t "show_tour" %>
      </h3>
    </div>
    <div class="box-body table-responsive no-padding">
      <table class="table table-responsive table-hover table-bordered border-user">
        <tr>
          <th><%= t "name" %></th>
          <td><%= @tour.name.truncate Settings.tours.truncate %></td>
        </tr>
        <tr>
          <th><%= t "tours.date_from" %></th>
          <td><%= @tour.date_from %></td>
        <tr>
          <th><%= t "tours.date_to" %></th>
          <td><%= @tour.date_to %></td>
        </tr>
        <tr>
          <th><%= t "tours.location_from" %></th>
          <td><%= @tour.location_from %></td>
        </tr>
        <tr>
          <th><%= t "tours.location_to" %></th>
          <td><%= @tour.location_to %></td>
        </tr>
        <tr>
          <th><%= t "tours.price" %></th>
          <td><%= @tour.price.round Settings.tours.round %></td>
        </tr>
        <tr>
          <th><%= t "image" %></th>
          <td>
             <% @images.each do |img| %>
              <%= image_tag img.image_link.url, class: "image_product" %>
            <% end %>
          </td>
        </tr>
      </table>
      <div class="text-right pages_custom">
        <%= paginate @images %>
      </div>
    </div>
  </div>
</div>

app/views/admin/tours/status.js.erb
$('#tour_status-<%= @tour.id %>').html("<%=  j render "admin/tours/status", tour: @tour %>");