config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    devise_for :users
    root "tours#index"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "sessions/new"
    resources :tours, only: %i(index show) do
      resources :bookings, except: %i(index), shallow: true
      resources :reviews, except: %i(index), shallow: true
    end
    resources :reviews, only: %i(index show) do
      resources :comments, only: %i(create destroy edit update)
    end
    resources :bookings, only: %i(index)
    resources :categories, only: %i(index show)
    namespace :admin do
      get "dasboard/index", to: "dasboard#index"
      patch "tours/status/:id", to: "tours#status", as: "status"
      resources :users
      resources :categories
      resources :tours
      resources :bookings
      resources :reviews
    end
  end
end

app/views/admin/layouts/_footer.html.erb
 <footer class="main-footer">
  <div class="pull-right hidden-xs">
    <b><%= t "app_name" %></b>
  </div>
  <strong><%= t "copy_right" %> <%= t "app_name" %></strong>
</footer>

app/views/admin/layouts/_header.html.erb
<header class="main-header">
  <p class="logo">
    <span class="logo-mini"><b><%= t "logo_mini" %></b></span>
    <span><b><%= link_to t("logo_lg_admin"), root_path, class: "logo" %></b></span>

  </p>
  <nav class="navbar navbar-static-top">
    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
      <span class="sr-only"><%= "menu" %></span>
    </a>
    <div class="navbar-custom-menu">
      <ul class="nav navbar-nav">
        <li>
          <%= link_to t("app.login.logout"), destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/admin/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
<%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>

app/views/admin/layouts/_sidebar.html.erb
<ul class="sidebar-menu" data-widget="tree">
  <li class="header"><%= t "menu" %></li>
  <li><%= link_to t("dasboard"), admin_dasboard_index_path, class:"fa fa-dashboard" %></li>
  <li><%= link_to t("user"), admin_users_path, class:"fa fa-user" %></li>
  <li><%= link_to t("category"), admin_categories_path, class:"fa fa-list-alt" %></li>
  <li><%= link_to t("tour"), admin_tours_path, class:"fa fa-car" %></li>
  <li><%= link_to t("booking"), admin_bookings_path, class:"fa fa-calendar" %></li>
  <li><%= link_to t("review"), admin_reviews_path, class:"fa fa-edit" %></li>
</ul>

app/views/admin/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %> | <%= t "app_name" %></title>
    <%= render "admin/layouts/rails_default"%>
  </head>
  <body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
      <%= render "admin/layouts/header" %>
      <aside class="main-sidebar">
        <section class="sidebar">
          <%= render "admin/layouts/sidebar" %>
        </section>
      </aside>
      <div class="content-wrapper">
      <section class="content">
        <% flash.each do |message_type, message| %>
          <div class="alert alert-<%= message_type %>"><%= message %></div>
        <% end %>
        <%= yield %>
      </section>
      </div>
      <%= render "admin/layouts/footer" %>
      <div class="control-sidebar-bg"></div>
    </div>
  </body>
</html>