config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    devise_for :users
    root "tours#index"
    get "/signup", to: "users#new"
    post "/signup", to: "users#create"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "sessions/new"
    resources :tours, only: %i(index show) do
      resources :bookings, except: %i(index), shallow: true
      resources :reviews, except: %i(index), shallow: true
    end
    resources :reviews, only: %i(index show) do
      resources :comments, only: %i(create destroy edit update)
    end
    resources :bookings, only: %i(index)
    resources :categories, only: %i(index show)
    namespace :admin do
      get "dasboard/index", to: "dasboard#index"
      patch "tours/status/:id", to: "tours#status", as: "status"
      resources :users
      resources :categories
      resources :tours
      resources :bookings
      resources :reviews
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :recoverable, :rememberable
  has_many :bookings, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, length: {maximum: Settings.size.length_max_name}
  validates :email, presence: true, length: {maximum: Settings.size.length_max_255},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  validates :password, presence: true,
    length: {minimum: Settings.size.min_password}, allow_nil: true
  validates :phone, presence: true
  validates :address, presence: true, length: {maximum: Settings.size.length_max_255}

  scope :show_user, -> {select :id, :name, :email, :phone, :address, :is_admin}
  scope :show_user_desc, -> {order created_at: :desc}
  scope :select_admin, -> {where is_admin: :true}
  scope :search_user, ->(search){
    search.squish! if search
    ransack(name_cont: search).result
  }
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :load_user, except: %i(new index create)

  def index
    params = search_params ? search_params[:name] : nil
    @pagy, @users = pagy(User.show_user.show_user_desc
      .search_user(params), items: Settings.page.page_number_admin)
  end

  def new
    @user = User.new
  end

  def show
    respond_to do |format|
      format.js
    end
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t "create_success"
      redirect_to admin_users_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update user_params
      flash[:success] = t "update_success"
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def destroy
    begin
      @user.destroy
      flash[:success] = t "delete_success"
    rescue
      flash[:danger] = t "not_delete"
    end
    redirect_to admin_users_path
  end

  private

  def user_params
    params.require(:user).permit :name,:email, :phone, :address, :is_admin,
      :password, :password_confirmation
  end

  def load_user
    @user = User.find_by id: params[:id]
    return if @user.present?
    flash[:danger] = t "not_user"
    redirect_to root_path
  end

  def search_params
    return nil unless params[:user_list]
    params.require(:user_list).permit :name
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: %i(new create)
  before_action :authenticate_user!, only: %i(edit update)
  before_action :correct_user, only: %i(edit update)

  def show; end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      log_in @user
      flash[:success] = t "app.sign_up.welcome"
      redirect_to @user
    else
      render :new
    end
  end

  def edit; end

  def update
    if @user.update user_params
      flash[:success] = t "app.users.profile_updated"
      redirect_to @user
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation, :phone, :address
  end

  def correct_user
    @user = User.find_by id: params[:id]
    redirect_to :root unless current_user? @user
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end

  def load_user
    @user = User.find_by id: params[:id]
    return if @user.present?
    flash[:danger] = t "app.users.not_found"
    redirect_to signup_path
  end
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user] do |f| %>
  <div class= "row">
    <%= render "admin/shared/error_messages", object: @user %>
  </div>
  <div class="box-body">
    <div class="row">
      <div class="col-sm-6 col-md-6 col-sx-12">
        <div class="form-group">
          <%= f.label :name, t("name") %><br>
          <div class="input-group">
            <span class="input-group-addon">
              <i class="fa fa-newspaper-o style-icon"></i>
            </span>
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :email, t("email") %><br>
          <div class="input-group">
            <span class="input-group-addon">
              <i class="fa fa-envelope-o style-icon"></i>
            </span>
            <%= f.text_field :email, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :phone, t("phone") %><br>
          <div class="input-group">
            <span class="input-group-addon">
              <i class="fa fa-phone-square style-icon"></i>
            </span>
            <%= f.text_field :phone, class: "form-control" %>
          </div>
        </div>
      </div>
      <div class="col-sm-6 col-md-6 col-sx-12">
        <div class="form-group">
          <%= f.label :address, t("address") %><br>
          <div class="input-group">
            <span class="input-group-addon">
              <i class="fa fa-globe style-icon"></i>
            </span>
            <%= f.text_field :address, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :password, t("password") %><br>
          <div class="input-group">
            <span class="input-group-addon">
              <i class="fa fa-unlock-alt style-icon"></i>
            </span>
            <%= f.text_field :password, class: "form-control" %>
          </div>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, t("confirmation") %><br>
          <div class="input-group">
            <span class="input-group-addon">
              <i class="fa fa-unlock-alt style-icon"></i>
            </span>
            <%= f.password_field :password_confirmation, class: "form-control" %>
          </div>
        </div>
      </div>
      <div class="col-sm-12 col-md-12 col-sx-12">
        <div class="form-group">
          <div class="input-group">
            <%= f.check_box :is_admin %>
            <span><%= t "is_admin" %></span>
          </div>
        </div>
        <%= f.submit t("submit"), class: "btn btn-primary button-full" %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/users/_show.html.erb
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span></button>
        <h4 class="modal-title"><%= t "show_user" %></h4>
      </div>
      <div class="modal-body">
        <table class="table table-hover table-bordered border-user">
          <thead class="bordered-blueberry">
            <tr>
              <th><%= t "name" %></th>
              <th><%= t "email" %></th>
              <th><%= t "phone" %></th></th>
              <th><%= t "address" %></th>
              <th><%= t "is_admin" %></th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td id="name"></td>
              <td id="email"></td>
              <td id="phone"></td>
              <td id="address"></td>
              <td id="isAdmin"></td>
              </td>
            </tr>
          </tbody>
          </thead>
        </table>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default pull-right" data-dismiss="modal"><%= t "tours.close" %></button>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/edit.html.erb
<% provide :title, t("edit_title_user") %>
<div class="col-xs-12">
  <div class="box">
    <div class="box-header">
        <h3 class="box-title"><%= t "edit_user" %></h3>
    </div>
    <%= render "admin/users/form" %>
  </div>
</div>

app/views/admin/users/index.html.erb
<% provide :title, t("admin_user") %>
<div class="col-sm-12 col-md-12 col-xs-12">
  <div class="box">
    <div class="box-header">
      <h3 class="box-title"><i class="fa fa-list-alt icon_user" id="icon_list"></i><%= t "list_admin" %></h3>
      <div class="box-tools">
        <%= form_tag admin_users_path, method: :get, class: "form-inline" do |f| %>
          <div class="input-group input-group-sm text-right" id="input_search">
            <%= text_field_tag  :name, nil, name: "user_list[name]", placeholder: t("look_for_user"), class: "form-control" %>
            <div class="input-group-btn">
              <%= button_tag :submit, class: "btn btn-default fa fa-search" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div class="box-body table-responsive no-padding">
      <table class="table table-hover table-bordered border-user">
        <thead class="bordered-blueberry table_color">
          <tr>
            <th class="index_number"><%= t "index" %></th>
            <th><%= t "name" %></th>
            <th><%= t "email" %></th>
            <th><%= t "phone" %></th></th>
            <th><%= t "address" %></th>
            <th><%= t "is_admin" %></th>
            <th class="text-right"><%= link_to t("add"), new_admin_user_path, class: "btn btn-primary fa fa-user-plus icon_add" %></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each_with_index do |user, index| %>
          <tr>
            <td><%= pages_number index, params[:page] %></td>
            <td><%= user.name %></td>
            <td><%= user.email %></td>
            <td><%= user.phone %></td>
            <td><%= user.address %></td>
            <td><%= user.is_admin == true ? "True" : "False" %></td>
            <td class="action">
              <%= link_to t("show"), admin_user_path(user), class: "btn btn-info fa fa-info-circle", remote: true %>
              <%= link_to t("edit"), edit_admin_user_path(user), class: "btn btn-success fa fa-edit"%>
              <% unless user.is_admin == true %>
                <%= link_to t("del"), admin_user_path(user), class: "btn btn-danger fa fa-trash", method: :delete,
                  data: {confirm: t("are_you_sure")} %>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
        </thead>
      </table>
      <div class="text-right pages_custom">
        <%== pagy_nav(@pagy) %>
      </div>
    </div>
  </div>
</div>
<%= render "show" %>

app/views/admin/users/new.html.erb
<% provide :title, t("new_title_user") %>
<div class="col-xs-12">
  <div class="box">
    <div class="box-header">
        <h3 class="box-title"><%= t "add_user" %></h3>
    </div>
    <%= render "admin/users/form" %>
  </div>
</div>

app/views/admin/users/show.js.erb
$("#name").text("<%= @user.name %>");
$("#email").text("<%= @user.email %>");
$("#phone").text("<%= @user.phone %>");
$("#address").text("<%= @user.address %>");
$("#isAdmin").text("<%= @user.is_admin %>");
$("#myModal").modal();